//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeAuth_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Owner { get; set; }
        public string Type { get; set; }
        public string Department_id { get; set; }
        public string Department_name { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<bool> Is_credential_authority { get; set; }
        public Nullable<bool> Is_attendance_manager { get; set; }
        public Nullable<bool> Is_information_collector { get; set; }
    }
}
