/*
 * Purpose: 
 * This class is auto-generated by Entity Framework when migrations are enabled for the project. 
 */

using System.Data.Entity.Migrations;

namespace QRCodeAuth_Web.Migrations
{
    internal sealed class Configuration : DbMigrationsConfiguration<QRCodeAuth_Web.Data.WebSystemData>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
			AutomaticMigrationDataLossAllowed = true;
		}

        protected override void Seed(QRCodeAuth_Web.Data.WebSystemData context)
        {

        }
    }
}
